# Generated by Django 4.2 on 2023-05-11 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraddress')),
            ],
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.useraddress'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
