# Generated by Django 4.2 on 2023-05-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='cardholder_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
