# Generated by Django 4.2 on 2023-05-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferImage',
        ),
    ]
