# Generated by Django 4.2 on 2023-05-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_delete_offerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='price',
        ),
    ]
