# Generated by Django 4.2 on 2023-05-11 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_unregistereduser_rename_countries_country_and_more'),
        ('menu', '0011_menuproduct_price_menuproduct_quantity_and_more'),
        ('shoppingcart', '0002_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=8)),
                ('payment_method', models.CharField(max_length=255)),
                ('cardholder_name', models.CharField(max_length=255, null=True)),
                ('card_number', models.CharField(max_length=255, null=True)),
                ('expiration_date', models.CharField(max_length=255, null=True)),
                ('cvc', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuproduct')),
                ('unregistered_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.unregistereduser')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.accountuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
