# Generated by Django 4.2 on 2023-05-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_alter_order_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
