# Generated by Django 4.2 on 2023-05-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0011_menuproduct_price_menuproduct_quantity_and_more'),
        ('offers', '0004_remove_offers_rating_offers_offer_image_offers_price_and_more'),
        ('shoppingcart', '0005_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuproduct')),
            ],
        ),
    ]
