# Generated by Django 4.2 on 2023-05-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='offer',
        ),
    ]
