# Generated by Django 4.2 on 2023-05-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuproduct_price_menuproductprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuToppingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='MenuProductPrice',
        ),
        migrations.AlterField(
            model_name='menutopping',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menutoppingtype'),
        ),
    ]
