# Generated by Django 4.2 on 2023-05-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menutoppingtype_delete_menuproductprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuproduct')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menusize')),
            ],
        ),
    ]
