# Generated by Django 4.2 on 2023-05-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuproductprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuproduct',
            name='size',
        ),
    ]
