# Generated by Django 4.2 on 2023-05-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuproducttopping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuproduct',
            name='topping',
        ),
    ]
