# Generated by Django 4.2 on 2023-05-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_menuproduct_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuproductprice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='menuproductprice',
            name='size',
        ),
        migrations.AddField(
            model_name='menuproductprice',
            name='price_large',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=6),
        ),
        migrations.AddField(
            model_name='menuproductprice',
            name='price_medium',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=6),
        ),
        migrations.AddField(
            model_name='menuproductprice',
            name='price_small',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=6),
        ),
        migrations.DeleteModel(
            name='MenuSize',
        ),
    ]
