# Generated by Django 4.2 on 2023-05-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menuproductprice_price_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuproductprice',
            name='price_large',
            field=models.DecimalField(decimal_places=0, default=3000, max_digits=6),
        ),
        migrations.AlterField(
            model_name='menuproductprice',
            name='price_medium',
            field=models.DecimalField(decimal_places=0, default=2000, max_digits=6),
        ),
        migrations.AlterField(
            model_name='menuproductprice',
            name='price_small',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=6),
        ),
    ]
