# Generated by Django 4.2 on 2023-05-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_menuproductprice_price_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuproduct',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1490, max_digits=8),
        ),
        migrations.AddField(
            model_name='menuproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='MenuProductPrice',
        ),
    ]
