# Generated by Django 4.2 on 2023-05-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_menuproduct_price_menuproduct_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('price', models.DecimalField(decimal_places=0, default=1490, max_digits=8)),
                ('offer_image', models.CharField(default='', max_length=9999)),
            ],
        ),
    ]
